import AuthProvider from "@/Providers/AuthProvider";
import ReactQueryProvider from "@/Providers/ReactQueryProvider";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "600", "500", "700", "800"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main>
          <ReactQueryProvider>
            <AuthProvider>
              <div>
                <Navbar />
              </div>
              <div className="">{children}</div>
            </AuthProvider>
          </ReactQueryProvider>
        </main>
      </body>
    </html>
  );
}
